syntax = "proto3";

package com.taotao.cloud.goods.api.grpc;
import "dto.proto";
option java_multiple_files = true;
option java_package = "com.taotao.cloud.goods.api.grpc";
option java_outer_classname = "GoodsSkuQueryGrpcServiceProto";
//option objc_class_prefix = "HLW";

// The device service definition.
service GoodsSkuQueryGrpcService {
  // Sends a message
  rpc queryGoodsSku (GoodsSkuGrpcQuery) returns (GoodsSkuGrpcResponse){}
}

// The request message .
message GoodsSkuGrpcQuery {
  string id = 1;
}


