syntax = "proto3";

package com.taotao.cloud.goods.api.grpc;
import "dto.proto";
option java_multiple_files = true;
option java_package = "com.taotao.cloud.goods.api.grpc";
option java_outer_classname = "GoodsSkuCommandGrpcServiceProto";
//option objc_class_prefix = "HLW";

service GoodsSkuCommandGrpcService {
  rpc createGoods (CreateGoodsSkuGrpcCommand) returns (GoodsSkuGrpcResponse){}
  rpc updateGoods (UpdateGoodsSkuGrpcCommand) returns (GoodsSkuGrpcResponse){}
}

message CreateGoodsSkuGrpcCommand {
  string id = 1;
}

message UpdateGoodsSkuGrpcCommand {
    string id = 1;
}



